### ISSUE TITLE
Multiple (2) roles per reaction?

### ISSUE THREAD

**Issue by rich1488** [eibex/reaction-light#100]
Is there an easy way to allow the bot to give multiple roles for each reaction?

I will try to explain the reason for this;

By default a Discord server allows each user to all categories and channels. Perhaps there is too many, so they allow users to react for roles that hide categories/channels. Which is a better method than reacting to see them.

For these roles that hide (or restrict) access to categories/channels, there could be numerous of them. To keep these roles organized, there is 1 main role above all these roles, like a header. For example it might be called `----HIDDEN----` and every role below this header means that role is hiding/restricting view permissions for the corresponding category/channel.

There is also an issue I can see with this- when users un-react to get access back to categ/chan the bot doesn't know better to not take away this header (`---HIDDEN---`) role. So it would need to know not to touch that header role unless all reactions from the user have been removed/un-reacted.

Hope this makes sense.

One might say "Why not just give that role on join?" which is a fair point. But heres 2 reasons- the first being your bot that gives auto role on join might only be capable of giving 1 role. The other reason is that the whole point of these roles are for channel organization, so users having the header (`---HIDDEN---`) role without having any roles under it, would look out of place.

**Comment by d7415** [comment]
Hi. The second role is not necessary in that instance. If you don't grant permission to the category, it will only show when the user has the View Channel permission for a channel in that category.

**Comment by eibex** [comment]
As d7415 stated you can deny view channels permissions by default and modify just one role to explicitly grant view channel permissions (and viceversa).

**Comment by rich1488** [comment]
Right, but what the `---HIDDEN---` is just a cosmetic role, to show in users list of roles that everything below it is what that user has hidden.

If one were to deny view perms for that role, then it would hide ALL those categories/channels.

For the example I used, theres 11 categories/channels that can be hidden by reacting to get the affiliated role. So if the one role denied perms, then it defeats the whole system.
![image](https://user-images.githubusercontent.com/87265195/151384485-403775fa-f2f9-4417-aa9b-c9b2d2adfd94.png)

**Comment by d7415** [comment]
Oh, I see. You're using it backwards.

That feels messy. You know that users can already mute categories and channels, and hide muted channels? That seems a far easier way to accomplish that.
