### ISSUE TITLE
Guild only commands missing error message

### ISSUE THREAD

**Issue by Edwinexd** [eibex/reaction-light#131]
**Describe the bug**

Guild only commands such as /help should print out that they only may be ran in a guild channel / include a message about limited functionality.

I'm currently unaware of which commands are affected.

**To Reproduce**

1. Run /help in direct messages
2. Unhandled key error gets raised

**Expected behavior**

Command executor receives an error message.

**Screenshots**
\-

**Server:**

- OS: N/A
- Python version: N/A
- disnake version: N/A

**Traceback**

```
# unable to retrieve at the moment, /help raises an attributerror since inter.guild is none
```

**Comment by Edwinexd** [comment]
(I attempted to self-assign this issue but didn't work)

**Comment by eibex** [comment]
> I'm currently unaware of which commands are affected.

I believe all commands that have an isadmin check are affected since they look up guild roles.
