### ISSUE TITLE
Replace hardcoded admin_a, b, c with a single list variable

### ISSUE THREAD

**Issue by eibex** [eibex/reaction-light#17]
**Is your feature request related to a problem? Please describe.**
I don't like the idea of manually adding more admins or using 0s in case you need less than 3.

It would be possible to have a single `admin` var in `config.ini` that is equal to all the admin role IDs separated by a comma.

`configparser` is not capable of reading lists from a var, but it is possible to use `.split(",")` on the string.

Then we could just make `isadmin()` check whether the ID is in the list or not.

**Describe the solution you'd like**
The real issue is making the bot update the old `config.ini` to the new one automagically so that hosters do not need to manually change the config file so that it matches the new Python file.

**Describe alternatives you've considered**
So far my ideas are:
- Make a new python file with a "migration" class that is imported at the start of `bot.py`. This could be used for this update and future ones, but if a user skips two "migrations" I would imagine the bot could break.
- Make a "migration" python file that users need to run manually (this will break the bot if a user just `rl!update` without reading the changelog though).
- Make the bot tell the user to apply the necessary changes if an exception is raised when parsing `config.ini`. This won't work if `systemchannel` is not set though.

I will try to think of more ways to handle this, but if anyone has ideas please feel free to share them.

**Comment by arbaes** [comment]
Actually couldnt this be solved by switching to SQLite too ?

BTW, I'll give a try at implementing it this weekend if I have some time :)

**Comment by eibex** [comment]
@arbaes That's a good point. I guess switching to SQLite makes the most sense.

If any kind of migration needs to happen it may as well include an actual database.

I will start playing around with the sqlite3 library as soon as I have some time and see how to implement it.
