### ISSUE TITLE
Update Broke the bot

### ISSUE THREAD

**Issue by PhantomNimbi** [eibex/reaction-light#34]
**Describe the bug**

Bot no longer starts after the latest update.

**Steps to reproduce the behavior:**

update to the current build and attempt to run the bot.

eg.
after updating open terminal and type:

```
cd /path/to/bot/
python3 bot.py
```
**A clear and concise description of what you expected to happen.**

I expected to bot to actually launch.

**If applicable, add screenshots to help explain your problem.**

https://imgur.com/ZjHoiIp.png

**Server:**

- OS: Debian
- Python version: 3.7.3
- discord.py version: don't know how to check this but i tend to keep it up to date.

**Traceback**

```
Traceback (most recent call last):
  File "bot.py", line 37, in <module>
    from core import database, migration, activity
  File "/home/admin/reaction-light/core/__init__.py", line 2, in <module>
    from .activities import *
ModuleNotFoundError: No module named 'core.activities'

```

**Comment by eibex** [comment]
Apologies, I thought I patched and I (strangely) didn't encounter that error while testing. I will patch it in a moment.

**Comment by PhantomNimbi** [comment]
Thanks it seems to be launching now =)
