### ISSUE TITLE
Cloning the Repository

### ISSUE THREAD

**Issue by AndrewNunnes** [eibex/reaction-light#45]
How would we clone the repository? Using git clone https://github.com/eibex/reaction-light.git

**Comment by eibex** [comment]
Yes, `git clone https://github.com/eibex/reaction-light.git` is correct.

You will need to have git installed. It comes pre-packaged on most Linux distributions. 

If you are on Windows you can get "git for windows" or simply download the GitHub app and use it to clone the repository.
