### ISSUE TITLE
Error in discord.py version 1.5.0

### ISSUE THREAD

**Issue by MEXXIO** [eibex/reaction-light#47]
**Describe the bug**

Is there a chance to upgrade to discord.py 1.5.0
In version 1.3.4 it is ok

**Server:**

- OS: MacOS
- Python version: 3.8.5
- discord.py version: 1.5.0

**Traceback**

```
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/Users/erwinowak/Desktop/reaction-light-master/bot.py", line 521, in on_raw_reaction_add
    await member.add_roles(role)
AttributeError: 'NoneType' object has no attribute 'add_roles'
```

**Comment by eibex** [comment]
Sorry, I have been terribly busy lately. I will look into it as soon as I can, hopefully this evening but it will be done by the end of the week.

**Comment by MEXXIO** [comment]
> Sorry, I have been terribly busy lately. I will look into it as soon as I can, hopefully this evening but it will be done by the end of the week at the latest.

I would be very grateful for your help. In return, when using the bot and the code itself, I will remember you everywhere.

**Comment by eibex** [comment]
Please read the CHANGELOG or the Setup section of the README to see what steps you need to manually do to get the bot working.
