### ISSUE TITLE
Notification on new role (guild)

### ISSUE THREAD

**Issue by DemOnJR** [eibex/reaction-light#50]
**Is your feature request related to a problem? Please describe.**

An user will not see the change when an new role is added and new category will appear because many servers are too "large" (infinete scroll).

**Describe the solution you'd like**

An private message when the user choose one of roles with an custom message.
Ex. You have an new role added: @Name, and new category access you can visit it here: #the-new-category

I don't have.

None.

**Comment by eibex** [comment]
The feature is now added with v2.3.0. Use `rl!notify` to toggle notifications on.

> and new category access you can visit it here: #the-new-category

This was too complex and probably required too many API calls to implement.
