### ISSUE TITLE
option for inverting reaction role function

### ISSUE THREAD

**Issue by traxell1** [eibex/reaction-light#51]
**Is your feature request related to a problem? Please describe.**

Not related to a problem.

**Describe the solution you'd like**

When users click on a reaction, they lose a role, instead of getting it assigned. unclicking regains them the role.

**Describe alternatives you've considered**

Haven't been able to come up with any.

**Comment by eibex** [comment]
This feature would require too many changes for what it needs to achieve. Sorry

**Comment by traxell1** [comment]
> This feature would require too many changes for what it needs to achieve. Sorry

Understood. On a separate note, wanted to give my thanks for the application. Great work!

**Comment by eibex** [comment]
> On a separate note, wanted to give my thanks for the application. Great work!

Glad you find it useful and enjoy it
