### ISSUE TITLE
missing brackets in database.py

### ISSUE THREAD

**Issue by kcoder63** [eibex/reaction-light#66]
**Describe the bug**

I was running this on my server, it was going smooth until I noticed this error in code.

![rec](https://user-images.githubusercontent.com/74637789/111310898-97c46380-8683-11eb-8e0f-3dcbcfec744e.png)

I would not like trespass here but to contribute, I would like to make the small change needed :)

**Comment by Edwinexd** [comment]
Hey! I don't see any issues with the code snippet you have provided, could you elaborate?

**Comment by kcoder63** [comment]
that should be `["reactionrole_id"]` and not `reactionrole_id`  right?

**Comment by d7415** [comment]
> that should be `["reactionrole_id"]` and not `reactionrole_id` right?

No. `reactionrole_id` is defined a few lines earlier. `["reactionrole_id"]` is just a single-item list containing that string.

**Comment by kcoder63** [comment]
oops sorry then, my mistake
