### ISSUE TITLE
Bot doesn't start

### ISSUE THREAD

**Issue by Hamm3rhart** [eibex/reaction-light#68]
**Describe the bug**

Unable to start the bot. ( I tried with 2 machines with fresh installations of the bot)

**To Reproduce**

Just try to run the bot with `python3 bot.py`

**Expected behavior**

Starting....

**Screenshots**

![grafik](https://user-images.githubusercontent.com/50116721/111478693-98ff9a00-8730-11eb-8b9a-0d1b9df4ee27.png)

**Server:**

- OS: Ubuntu 4.15.0-136-generic
- Python version: Python 3.6.9
- discord.py version: 1.6.0

**Traceback**

```
File "<fstring>", line 1
    ((await getchannel(system_channel)).mention if system_channel else 'none')
                     ^
SyntaxError: invalid syntax

```

**Comment by eibex** [comment]
Weirdly enough my bot (which runs master) started without issues, hence why I didn't notice it.
I merged a fix now.
