### ISSUE TITLE
The bot deletes reactionroles although the message still exists.

### ISSUE THREAD

**Issue by Shmalle** [eibex/reaction-light#73]
**Bot deletes Reactionroles though the messages still exist**

What happens is, that the bot starts deleting stored Reactionroles for messages that still exists, with the reason, that the message got deleted. In fact, the message didnt get deleted. Its still existing. 

**To Reproduce**

This happened to me when restarting the bot multiple times, each restart made it delete 1 reactionrole. This happened locally, but when running on my Windows VPS 2019, it just did the same thing without any restarts.

**Expected behavior**

The Bot will delete the Rectionrole

**Screenshots**

*None*

**Server:**

- OS: Windows 10 20H2 / Windows 10 2019 Server
- Python version: 3.8.9
- discord.py version: 1.6

**Traceback**

```
Theres no traceback since there isnt any error that came up in console.
```

**Comment by eibex** [comment]
Hi, thanks for the bug report. Did all reactions stop working for a given message or just some of them?

**Comment by eibex** [comment]
Also, did the bot report anything in your system channel? (if you set it up)

**Comment by Shmalle** [comment]
> Hi, thanks for the bug report. Did all reactions stop working for a given message or just some of them?

@eibex the whole message got "killed".

> Also, did the bot report anything in your system channel? (if you set it up)

I got an error there as well, I was able to set an overall-bot-channel but not a local-server-systemchannel. See screenshot.
https://cdn.discordapp.com/attachments/831969769095692341/836302791928053770/unknown.png

**Comment by eibex** [comment]
Hi, the local server system channel error was fixed now. You can update the bot now on master branch or wait until the next release.
I will try to dig more on the core issue of your report as I cannot really reproduce this on my systems.

* So every time you restart the bot (or every 24 hours after you boot it up) one message gets deleted (and only one message?)?
* Does the bot have access to the channel the "deleted" message is in?
* What permissions does the bot have?

**Comment by eibex** [comment]
Given that no new information was provided and the issue cannot be replicated I will close this for now.
