### ISSUE TITLE
how to run it 24/7

### ISSUE THREAD

**Issue by indmohit** [eibex/reaction-light#75]
How may i run it 24/7 any idea

**Comment by d7415** [comment]
In short, run it on a computer that runs 24/7. That could be yours, or maybe a VPS.

**Comment by eibex** [comment]
You have to run bot.py and keep it running. As @d7415 said you either need a PC to be on 24/7. This is more achievable with a cheap VPS.

On Linux you can run it as a background task allowing you to close the terminal with either `nohup` or `tmux`.
