### ISSUE TITLE
Click on USE existing text in new installation ends in loop

### ISSUE THREAD

**Issue by ChaosEmpire** [eibex/reaction-light#76]
I just installed the bot
added with the new command my first reactions

at the point use existing text or make new one
i choose the icon to use and existing, believing there is some default

now i cant proceed further, so i restarted the bot and tried the edit command
i have to enter a channel and always get the information

There are no reaction-role messages in that channel.

**Comment by eibex** [comment]
I have just tested this and it is working properly.

After you select 🗨️, are you reacting to your message of choice with 🔧 (`:wrench:`) as described in the instructions?

**Comment by d7415** [comment]
To clarify a couple of points:

> i choose the icon to use and existing, believing there is some default

Existing means use an existing message on the server - you then go and mark the one you want.

> now i cant proceed further, so i restarted the bot and tried the edit command
> i have to enter a channel and always get the information
> 
> There are no reaction-role messages in that channel.

The edit existing won't work if you haven't finished the initial set up of a message.

**Comment by ChaosEmpire** [comment]
the new command goes step by step
one point is the question
use an existing message, or create a new one (the robot)
I clicked the chat symbol
and it id..there is no message

but from there. i cant go further..i cant react on a not existing message with the tool emoji

and i cant finish the initial setup...if i dont add a message during the new setup wizard, 

i would suggest to add a default message OR just better
react after the click on the chat bubble with..sorry there is no existing message
do you want to create a new one , or do you want to use a default ...

**Comment by Edwinexd** [comment]
Hey! I think you are misinterpreting the existing message term, by an existing message it is referring to ANY message in the current guild (aka messages sent by you, other members and/or bots)

**Comment by eibex** [comment]
> i would suggest to add a default message

Try the other option, instead of the "chat bubble"
