### ISSUE TITLE
Help! Slash Commands Not Registering

### ISSUE THREAD

**Issue by Ravost99** [eibex/reaction-light#99]
Pls help:

Slash Commands not registering in servers

**Screenshots**

![in-dms](https://user-images.githubusercontent.com/75264908/147521600-a540ef6c-5a0e-4d1b-b791-eb6ba44e7e56.png)
![slash-in-server](https://user-images.githubusercontent.com/75264908/147521601-8ec26689-60e1-4ef3-842c-33d8ded44946.png)

**Server & Bot:**

- OS: Windows 10
- Python version: v3.8.2
- discord.py version: v1.7.3

**Traceback**

No Error

Pls help me
I have never used disnake, but i have used discord.py and dislash.py

**Comment by Edwinexd** [comment]
Hey!
This is most likely caused by the bot missing the application.commands scope in the target guild, try to re-authorize it with: `https://discord.com/oauth2/authorize?&client_id=CLIENT_ID&scope=bot%20applications.commands&permissions=2415978560` (replace CLIENT_ID)

**Comment by Ravost99** [comment]
Thanks it worked!!! TYSM
